Portmap:
  guide: >
    포트맵 공격은 주로 RPC 포트(111)를 대상으로 하는 스캔 시도입니다.
    - 방화벽에서 포트 111 차단
    - RPC 서비스 비활성화
    - IDS 룰 설정 권장

UDP:
  guide: >
    UDP 플러드 공격은 대량의 UDP 트래픽을 전송해 서비스 거부를 유발합니다.
    - 비정상 UDP 트래픽 필터링
    - UDP 응답 차단 및 속도 제한 설정
    - UDP 서비스 포트 최소화

MSSQL:
  guide: >
    MSSQL 공격은 SQL Server 서비스 포트를 노리는 트래픽으로, DB 서버 마비를 유발할 수 있습니다.
    - 포트 1433 차단
    - 외부 접근 제한 및 인증 설정 강화
    - DB 접근 로그 실시간 모니터링

NetBIOS:
  guide: >
    NetBIOS 공격은 윈도우 공유 서비스(NetBIOS)를 노려 취약점을 탐색하거나 감염을 시도합니다.
    - 포트 137, 138, 139 차단
    - NetBIOS 서비스 비활성화
    - SMB 프로토콜 보안 패치 적용

BENIGN:
  guide: >
    정상 트래픽으로 판단됩니다. 별다른 조치는 필요하지 않습니다.

Unknown:
  guide: >
    알 수 없는 유형의 공격입니다. 네트워크 관리자에게 확인이 필요합니다.
